### ISSUE TITLE
Integration Testing & Serialization of MockUser 

### ISSUE THREAD

**Issue by metaskills** [fphilipe/warden-github-rails#16]
I've noticed that if when I create a `Warden::GitHub::Rails::TestHelpers::MockUser` and pass that to `login_as` and visit my page, it works fine. However, only when I call `#stub_membership` with something like `org: 'customink'`, it blows up with:

```
NoMethodError: undefined method `{"team"=>[], "org"=>["customink"]}=' for #<Warden::GitHub::User:0x007ff4091a2a20>
    warden-github (1.2.0) lib/warden/github/user.rb:22:in `block in marshal_load'
    warden-github (1.2.0) lib/warden/github/user.rb:22:in `each'
    warden-github (1.2.0) lib/warden/github/user.rb:22:in `marshal_load'
    warden-github (1.2.0) lib/warden/github/verifier.rb:18:in `block in deserialize'
    warden-github (1.2.0) lib/warden/github/verifier.rb:17:in `tap'
    warden-github (1.2.0) lib/warden/github/verifier.rb:17:in `deserialize'
    warden-github (1.2.0) lib/warden/github/verifier.rb:9:in `load'
```

Still trying to figure this out.

**Comment by metaskills** [comment]
OK... here are the changes I made. Note I am in a Rails 5 edge app that is using the default :json cookies_serializer. This below is my patch to the github-warden project. If this technique looks valid, then maybe I should open a PR on their Verifier class that allows a class attribute that allows this project to set the `Warden::GitHub::Rails::TestHelpers::MockUser` as the `deserialize_class` to avoid monkey patching.

```ruby
module Warden
  module GitHub
    class Verifier

      def deserialize(key)
        Warden::GitHub::Rails::TestHelpers::MockUser.new.tap do |u|
          u.marshal_load(cookie_verifier.verify(key))
        end
      rescue ::ActiveSupport::MessageVerifier::InvalidSignature
        nil
      end

    end
  end
end
```

This patch is to this projects `MockUser`. It makes sure to symbolize the keys of the incoming JSON so other methods which use symbols can work.

```ruby
module Warden
  module GitHub
    module Rails
      module TestHelpers
        class MockUser < User

          def marshal_load(data)
            @memberships, super_data = data
            @memberships.symbolize_keys!
            super(super_data)
          end

        end
      end
    end
  end
end
```

**Comment by fphilipe** [comment]
Could you show me the code of how you're stubbing the memberships? That first error message strikes me as odd. :confused:

**Comment by metaskills** [comment]
Sure... it looks like this.

```ruby
def github_user_metaskills
  Warden::GitHub::Rails::TestHelpers::MockUser.new.tap do |user|
    user.attribs = {
      id: 2381,
      login: "metaskills",
      avatar_url: "https://avatars.githubusercontent.com/u/2381?v=3",
      site_admin: false,
      name: "Ken Collins",
      company: "CustomInk.com",
      email: "ken@metaskills.net"
    }
    user.token = "9e47516d3f26fba33b2dddbbd940d1f616d2e7e7"
    user.browser_session_id = nil
    user.stub_membership org: 'customink'
  end
end
```

**Comment by fphilipe** [comment]
@metaskills Found the bug. See link above to atoms/warden-github.
